Timebug
nat/keyrace pull request #22
Opened 2021-02-19 06:32 UTC by Skylerwiernik

Fixed an issue where timechart did not properly roll over between days, and crashed the program (and slowed down the users computer significantly) between 12:00 am and 12:19 am. Also fixed an issue where midnight was displayed as '0am'.

2021-02-19 16:16 UTC, nat commented on mac/keyrace-mac/keyrace_macApp.swift
> +            minutes.replaceSubrange(1420..<1440, with: repeatElement(0, count: 20)) // Deletes the last 20 minutes of the previous day
Would probably be better not to run this on every keypress between 1am and 11pm :-)

2021-02-19 16:17 UTC, nat requested changes
Fix the comment in increment() and this looks good!

2021-02-19 21:36 UTC, nat approved these changes

2021-02-19 21:36 UTC, merged

2021-02-21 08:10 UTC, jessfraz commented
Still is panicking for me during the first 20 min after midnight ;)

on this line:
```
currMin - i > 0 ? mins.append(minutes[currMin - i]): mins.append(minutes[1440 + i - (20 - currMin)])
```

specifically
```
minutes[1440 + i - (20 - currMin)]
```

I can fix it, but figured you might want to